spring:
  datasource:
#    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/postgres?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
#  sql:
#    init:
#      schema-locations:
#        - classpath:db/table.sql
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  output:
    ansi:
      enabled: always


mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true